---
driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['KITCHEN_AWS_KEY'] %>
  security_group_ids: [<%= ENV['KITCHEN_SECURITY_GROUP'] %>]
  region: <%= ENV['KITCHEN_AWS_REGION'] %>
  availability_zone: <%= ENV['KITCHEN_AWS_AVAILABILITY_ZONE'] %>
  require_chef_omnibus: <%= ENV['KITCHEN_OMNIBUS_BOOL'] %>
  subnet_id: <%= ENV['KITCHEN_SUBNET'] %>
  iam_profile_name: <%= ENV['KITCHEN_IAM'] %>
  instance_type: <%= ENV['KITCHEN_SIZE'] %>
  associate_public_ips: <%= ENV['KITCHEN_PUBLIC_IP_BOOL'] %>
  interface: <%= ENV['KITCHEN_NETWORK_INTERFACE'] %>
  tags:
    Name: <%= ENV['KITCHEN_INSTANCE_NAME_TAG'] %>
    Cookbook: eldus-tomcat
    Cookbook_Version: 0.1.0
    Developer: ldesiqueira


provisioner:
  name: <%= ENV['KITCHEN_PROVISIONER'] %>

transport:
  username: <%= ENV['KITCHEN_USERNAME'] %>
  ssh_key: <%= ENV['KITCHEN_PRIVATE_KEY_PATH'] %>

platforms:
  - name: <%= ENV['KITCHEN_EC2_PLATFORM'] %>
    driver:
      image_id: <%= ENV['KITCHEN_EC2_AMI'] %>

suites:
  - name: default
    run_list:
      - recipe[eldus-tomcat::default]
    attributes:
